name: 'JUnit Platform Console Launcher'
description: 'Download and start the JUnit Platform Console Launcher'
inputs:
  platform-version:
    description: 'Version of the JUnit Platform modules and standalone artifact'
    required: true
    default: '1.6.0'
outputs:
  standalone-jar:
    description: 'The path of the downloaded JUnit Platform Console Standalone JAR file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.platform-version }}
