name: 'JUnit Platform Console Launcher'
description: 'Download and start the JUnit Platform Console Launcher'
inputs:
  version: # id of input
    description: 'Version of the JUnit Platform'
    required: true
    default: '1.6.0-RC1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
