name: test
on: push
jobs:
  jdk:
    name: "JDK ${{ matrix.java }}"
    strategy:
      fail-fast: false
      matrix:
        java: [8]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - uses: ./
    - run: java -version
